version: '3.3'
services:
  zfile:
    image: zhaojun1998/zfile-pro
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - '/root/zfile-pro/db:/root/.zfile-v4/db'
      - '/root/zfile-pro/logs:/root/.zfile-v4/logs'
      - '/root/zfile-pro/file:/data/file'
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true