version: '3.3'
services:
  zfile:
    image: mlikiowa/napcat-docker:v1.5.4
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - "1panel-network"
    ports:
      - "${PANEL_APP_PORT_HTTP}:3001"
      - "${PANEL_APP_PORT_HTTP1}:6099"
    volumes:
      - '/usr/local/share/napcat://usr/src/app/napcat/config'
    environment:
      ACCOUNT: ${ACCOUNT}
      WS_ENABLE: ${WS_ENABLE}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true