version: '3.3'
services:
  zfile:
    image: fantasy325/auto:v0.2
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - "1panel-network"
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - '/usr/local/share/Auto/user.db:/user.db'
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true