version: '3.3'
services:
  zfile:
    image: zhaojun1998/zfile-pro:4.1.6
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "./data/db:/root/zfile-pro/.zfile-v4/db"
      - "./data/logs:/root/zfile-pro/.zfile-v4/logs"
      - "./data/mnt:/data/zfile-pro/file"
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
