version: '3.3'
services:
  zfile:
    image: zhaojun1998/zfile-pro:4.3.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - "1panel-network"
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - '/root/Zfile-Pro/db:/root/.zfile-v4/db'
      - '/root/Zfile-Pro/logs:/root/.zfile-v4/logs'
      - '/root/Zfile-Pro/file:/data/file'
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true