version: '3'
services:
  neteasemusic:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
      - "${PANEL_APP_PORT_HTTPS}:8081"
    volumes:
      - "${DATA_PATH}/server.crt:/data/ssl/server.crt"
      - "${DATA_PATH}/server.key:/data/ssl/server.key"
    environment:
      - ENABLE_FLAC=true
      - ENABLE_LOCAL_VIP="cvip"
      - ENABLE_HTTPDNS=false
      - BLOCK_ADS=false
      - DISABLE_UPGRADE_CHECK=true
      - FOLLOW_SOURCE_ORDER=true
      - JSON_LOG=false
      - MIN_BR=320000
      - SELECT_MAX_BR=true
      - LOG_LEVEL=debug
      - SEARCH_ALBUM=true
      - SIGN_CERT=/data/ssl/server.crt
      - SIGN_KEY=/data/ssl/server.key
    #command: ["-o", "bilibili"]  # 设置要传递给容器的参数
    image: pan93412/unblock-netease-music-enhanced:v0.27.4-patch.1
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
