name: Renovate

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger Renovate'
        default: ''

jobs:
  renovate:
    runs-on: ubuntu-0.27.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          useSlim: false
          token: ${{ secrets.GITHUBTOKEN }}
